apiVersion: v1
kind: Service
metadata:
  name: tb-coap-loadbalancer
  namespace: thingsboard
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: tb-coap-transport
  ports:
    - port: 5683
      targetPort: 5683
      name: coap
      protocol: UDP
    - port: 5684
      targetPort: 5684
      name: coaps
      protocol: UDP